# Generated by Django 2.2.6 on 2019-12-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0004_auto_20191201_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
