# Generated by Django 2.2.6 on 2019-12-01 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giohang', '0001_initial'),
        ('dathang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giohang.Cart'),
        ),
    ]
